### ISSUE TITLE
Active maintainers?

### ISSUE THREAD

**Issue by jacobherrington** [elevatorup/solidus_searchkick#7]
Hey @GeorgeKaraszi it looks like you're the only member of elevatorup, is this repo actively maintained?

**Comment by jacobherrington** [comment]
@thejbsmith?

**Comment by jacobherrington** [comment]
For posterity @joshua-honig seems to be working on this repo now :)

**Comment by schaapy** [comment]
hey @jacobherrington I thought I'd jump in and give ya a quick update. We built this for a project we did awhile back and wanted to release what we did to everyone else. @joshua-honig @GeorgeKaraszi and @altereagle are developers here that you can bug on things and they'll be jumping into this project here soon. 

Sorry for the radio silence.
